/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ArticleContent: typeof import('./src/components/ArticleContent.vue')['default']
    ArticleHeader: typeof import('./src/components/ArticleHeader.vue')['default']
    CatalogueCard: typeof import('./src/components/CatalogueCard.vue')['default']
    FeaturedCarousel: typeof import('./src/components/FeaturedCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SubTitle: typeof import('./src/components/SubTitle.vue')['default']
    TiptapEditor: typeof import('./src/components/TiptapEditor.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
