/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/catalogue': RouteRecordInfo<'/catalogue', '/catalogue', Record<never, never>, Record<never, never>>,
    '/compte': RouteRecordInfo<'/compte', '/compte', Record<never, never>, Record<never, never>>,
    '/connexion': RouteRecordInfo<'/connexion', '/connexion', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/creer': RouteRecordInfo<'/creer', '/creer', Record<never, never>, Record<never, never>>,
    '/faq': RouteRecordInfo<'/faq', '/faq', Record<never, never>, Record<never, never>>,
    '/mentions': RouteRecordInfo<'/mentions', '/mentions', Record<never, never>, Record<never, never>>,
    '/mes-ressources': RouteRecordInfo<'/mes-ressources', '/mes-ressources', Record<never, never>, Record<never, never>>,
    '/ressources/[id]': RouteRecordInfo<'/ressources/[id]', '/ressources/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/catalogue.vue': {
      routes: '/catalogue'
      views: never
    }
    'src/pages/compte.vue': {
      routes: '/compte'
      views: never
    }
    'src/pages/connexion.vue': {
      routes: '/connexion'
      views: never
    }
    'src/pages/contact.vue': {
      routes: '/contact'
      views: never
    }
    'src/pages/creer.vue': {
      routes: '/creer'
      views: never
    }
    'src/pages/faq.vue': {
      routes: '/faq'
      views: never
    }
    'src/pages/mentions.vue': {
      routes: '/mentions'
      views: never
    }
    'src/pages/mes-ressources.vue': {
      routes: '/mes-ressources'
      views: never
    }
    'src/pages/ressources/[id].vue': {
      routes: '/ressources/[id]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
